blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/TSRwqx4K2v
    about: Join Web3Community, a community focusing on decentralized applications, web3, blockchain, open source technologies, collaboration, and fun chats with community members.
